language: ruby

matrix:
  include:
    - rvm: 2.2
      gemfile: gemfiles/rails4.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails3.gemfile
    - rvm: 2.2
      gemfile: gemfiles/no_framework.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/no_framework.gemfile

bundler_args: --without=guard

script:
  - bundle exec rake
  - bundle exec rubocop || echo 'rubucop complained about stuff'

addons:
  code_climate:
    repo_token: b1e6a3b1e048f93445138e722a1b822790c4349e521eade5facc833214e67547
