language: ruby

rvm:
  - 2.2
  - 2.1
  - 1.9.3

bundler_args: --without=guard

script:
  - bundle exec rake
  - bundle exec rubocop || echo 'rubucop complained about stuff'

addons:
  code_climate:
    repo_token: b1e6a3b1e048f93445138e722a1b822790c4349e521eade5facc833214e67547
